# Generated by Django 4.0.4 on 2022-05-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftErrorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('Usual', 'Usual'), ('Easy', 'Easy'), ('Hard', 'Hard')], max_length=50)),
                ('type', models.CharField(choices=[('Lower A', 'Lower A'), ('Lower B', 'Lower B'), ('Paired A', 'Paired A'), ('Paired B', 'Paired B'), ('Upper A', 'Upper A'), ('PreLegend', 'PreLegend'), ('Legend', 'Legend'), ('Repeat Legend', 'Repeat Legend'), ('Warning', 'Warning')], max_length=50)),
                ('aircraft', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Finished', 'Finished'), ('In progress', 'In progress'), ('Started', 'Started'), ('Kickback', 'Kickback'), ('Suspend', 'Suspend')], max_length=50)),
                ('errors_count', models.IntegerField(default=0)),
                ('info_count', models.IntegerField(default=0)),
            ],
        ),
    ]
